services:
   db:
     image: mariadb
     environment:
       MARIADB_ROOT_PASSWORD: pass
       MARIADB_DATABASE: wordpress
       MARIADB_USER: wordpress
       MARIADB_PASSWORD: pass

   wordpress:
     depends_on:
       - db
     build:
      context: ./docker/wordpress-php8
     healthcheck:
      test: [ "CMD-SHELL", "test -f /tmp/wordpress.healthcheck-passed || (curl -f -I http://wordpress.example.org && touch /tmp/wordpress.healthcheck-passed)" ]
      interval: 5s
      timeout: 10s
      retries: 20
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: pass
       WORDPRESS_CONFIG_EXTRA: |
        define('DISABLE_WP_CRON', true);
        define('COOKIE_DOMAIN', '.example.org');
     volumes:
       - ./wp-cassify:/var/www/html/wp-content/plugins/wp-cassify
     networks:
       default:
         aliases:
           - wordpress.example.org
           - wordpress1.example.org
           - wordpress2.example.org

   openldap:
     image: osixia/openldap:1.5.0
     environment:
       LDAP_DOMAIN: "example.org"
     command: --copy-service
     volumes:
      - ./docker/ldap-config:/container/service/slapd/assets/config/bootstrap/ldif/custom

   cas:
     build:
       context: .
       dockerfile_inline: |
         FROM esupportail/apereo-cas-ldap:7.3.5
         RUN apt-get update && apt-get -y install curl
     healthcheck:
       test: [ "CMD-SHELL", "test -f /tmp/cas.healthcheck-passed || (curl -fs http://cas.example.org:8080/cas/login | grep -q username && touch /tmp/cas.healthcheck-passed)" ]
       interval: 5s
       timeout: 10s
       retries: 20
     volumes:
       - ./docker/cas-config:/etc/cas
       - ./docker/cas-config/tmp-cas:/tmp/cas
     ports:
       - "8080:8080"
     depends_on:
       - openldap
     networks:
       default:
         aliases:
           - cas.example.org

   playwright-suite:
     build:
       context: ./docker/playwright-tests
     depends_on:
       wordpress:
           condition: service_healthy
       cas:
           condition: service_healthy
     command: ["sh", "-lc", "xvfb-run -a npm run test:e2e:headed && npm run show-report:docker"]
     ports:
       - "9323:9323"
     volumes:
       - ./docker/playwright-tests/playwright-report:/work/playwright-report
       - ./docker/playwright-tests/test-results:/work/test-results
     shm_size: 1gb


