services:

  wordpress:
     build:
      context: ./docker/wordpress-xdebug
     environment:
       XDEBUG_CONFIG: client_host=172.17.0.1      
     volumes:
       - type: bind
         source: ./wordpress
         target: /var/www/html
