services:

  wordpress:
     build:
      context: ./docker/wordpress-xdebug
     environment:
       XDEBUG_CONFIG: discover_client_host=true
       WORDPRESS_DEBUG: true
     volumes:
       - type: bind
         source: ./wordpress
         target: /var/www/html
