name: Docker Selenium Tests for wordpress (php7)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: php7 run selenium tests in dockers env and stop it
      run: docker compose -f docker-compose.yml -f docker-compose-php7.yml  up --abort-on-container-exit
