name: Docker Playwright Tests for wordpress multisite (php8)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: php8 run multisite playwright tests in dockers env and stop it
      run: docker compose -f docker-compose.yml -f docker-compose-multisite.yml up --build --abort-on-container-exit
    - name: Upload Playwright multisite report and results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-multisite-php8
        path: docker/playwright-tests/playwright-report
        if-no-files-found: ignore

